[package]
name = "leiterli"
version = "0.1.0"
authors = ["Samuel Peter <sapeter@ethz.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.*"
clap = "2.*"